name: Update cms/master

on:
  push:
    branches:
      - testo1

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Build with Maven
        run: mvn -B package --file pom.xml
  update-main-branch:
    needs: test
    name: Merge testo1 into main after tests run successfully
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ github.token }}
          source: 'testo1'
          target: 'main'
